version: 2.1

jobs:
  cloud-build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: echo "Hi, This is the cloud build"
      - run:
          name: Run the local script
          command: src/runlocal.sh
  lab-test:
    machine: true
    resource_class: orlenko/sample-local-station-runner2
    steps:
      - checkout
      - run: echo "Hello there, I am running on the local machine $HOST"
      - run:
          name: Run the local script
          command: |
            src/runlocal.sh
            src/success-test-on-machine.sh
            run-test.sh
      - store_test_results:
          path: src/test-ci
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: echo "Did we run everything?"
      - run:
          name: Run the local script
          command: src/runlocal.sh
workflows:
  build-workflow:
    jobs:
      - cloud-build
      - lab-test
      - build:
          requires:
            - cloud-build
            - lab-test
