version: 2.1

jobs:
  cloud-build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: echo "XXX— Hi This is the cloud on host $HOST"
  lab-test:
    machine: true
    resource_class: orlenko/sample-local-station-runner
    steps:
      - run: echo "XXX— Hello there, I am running on the local machine $HOST"
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run: echo "XXX— Did we run everything?"
workflows:
  build-workflow:
    jobs:
      - cloud-build
      - lab-test
      - build:
          requires:
            - cloud-build
            - lab-test
